### ISSUE TITLE
12-node Sedona entrypoints missing from DI wiring

### ISSUE THREAD

**Issue by jathavaan** [kartAI/doppa-data#359]
## Bug

The 12-node Sedona broadcast and partitioned entrypoint modules were not added to `container.wire()` in `app_config.py` when the 12-node experiments were introduced in #357. All other node counts (2, 4, 8, 16) are wired.

This causes `@inject`-decorated functions to receive an unresolved `Provide` proxy instead of the actual `IDatabricksService`, resulting in:

```
AttributeError: 'Provide' object has no attribute 'create_cluster'
```

## Fix

Add the two missing modules to the wiring list in `src/presentation/configuration/app_config.py`:
- `national_scale_spatial_join_databricks_broadcast_12_nodes`
- `national_scale_spatial_join_databricks_partitioned_12_nodes`
